#!/bin/bash

#[ Script ]--------------------------------------------------------------------#
#                                                                              #
# tinyagent                                                                    #
#                                                                              #
# PT-br:                                                                       #
# Script  para  facil  coleta  de dados de CPU, Memoria, Disco, Load, Uptime e #
# Interfaces de Rede                                                           #
#                                                                              #
# ----------------------------                                                 #
#                                                                              #
# EN:                                                                          #
# Script  for  easy  data  collection  of  CPU, Memory, Disk, Load, Uptime and #
# Network Intarfaces                                                           #
#                                                                              #
# reimlima@gmail.com                                                           #
# $Id: tinyagent,v 2 2015/05/04 reimlima Exp reimlima $                        #
#                                                                              #
#[ License ]-------------------------------------------------------------------#
#                                                                              #
# Copyright (c) 2015 Reinaldo Marques de Lima reimlima@gmail.com               #
#                                                                              #
# PT-br:                                                                       #
# A permissão  é  concedida,  a título gratuito, a qualquer pessoa que obtenha #
# uma   cópia   deste   software   e   arquivos   de  documentação  associados #
# (o "Software"),  para  lidar  com  o  Software sem restrição, incluindo, sem #
# limitação,  os  direitos  de  usar,  copiar,  modificar,  mesclar, publicar, #
# distribuir,  sublicenciar,  e / ou vender cópias do Software, e permitir que #
# as  pessoas  a  quem  o  Software  é fornecido o façam, sujeito às seguintes #
# condições:                                                                   #
#                                                                              #
# O  aviso de copyright acima e este aviso de permissão devem ser incluídos em #
# todas as cópias ou partes substanciais do Software.                          #
#                                                                              #
# O  SOFTWARE É FORNECIDO "COMO ESTÁ", SEM GARANTIA DE QUALQUER TIPO, EXPRESSA #
# OU  IMPLÍCITA,  INCLUINDO,  SEM  LIMITAÇÃO, AS GARANTIAS DE COMERCIALIZAÇÃO, #
# ADEQUAÇÃO  A  UM  DETERMINADO  FIM E NÃO VIOLAÇÃO. EM NENHUM CASO OS AUTORES #
# OU  DIREITOS AUTORAIS TITULARES  SERÃO RESPONSÁVEIS POR QUALQUER RECLAMAÇÃO, #
# DANOS  OU  OUTRAS  RESPONSABILIDADES,  SEJA  EM  UMA  AÇÃO DE CUMPRIMENTO DE #
# CONTRATO OU DE OUTRA FORMA, DECORRENTE DE, OU EM CONEXÃO COM O SOFTWARE OU O #
# USO OU OUTRAS FUNÇÕES DO SOFTWARE.                                           #
#                                                                              #
# Exceto  conforme  contido no presente aviso, o nome do (s) dos detentores de #
# direitos  autorais acima não devem ser utilizados em publicidade ou de outra #
# forma  para  promover  a venda, uso ou outras negociações deste Software sem #
# autorização prévia por escrito.                                              #
#                                                                              #
# ----------------------------                                                 #
#                                                                              #
# EN:                                                                          #
# Permission is hereby granted, free of charge, to any person obtaining a copy #
# of  this  software  and  associated  documentation  files  (the "Software"), #
# to  deal  in  the Software without restriction, including without limitation #
# the  rights  to  use,  copy, modify, merge, publish, distribute, sublicense, #
# and/or  sell  copies  of  the  Software,  and  to permit persons to whom the #
# Software is furnished to do so, subject to the following conditions:         #
#                                                                              #
# The  above  copyright notice and this permission notice shall be included in #
# all copies or substantial portions of the Software.                          #
#                                                                              #
# THE  SOFTWARE  IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR #
# IMPLIED,  INCLUDING  BUT  NOT  LIMITED TO THE WARRANTIES OF MERCHANTABILITY, #
# FITNESS  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE #
# AUTHORS  OR  COPYRIGHT  HOLDERS  BE  LIABLE  FOR ANY CLAIM, DAMAGES OR OTHER #
# LIABILITY,   WHETHER   IN   AN   ACTION  OF  CONTRACT,  TORT  OR  OTHERWISE, #
# ARISING FROM,  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER #
# DEALINGS IN THE SOFTWARE.                                                    #
#                                                                              #
# Except  as  contained  in  this  notice,  the name(s) of the above copyright #
# holders  shall  not be used in advertising or otherwise to promote the sale, #
# use or other dealings in this Software without prior written authorization.  #
#                                                                              #
#[ Changelog ]-----------------------------------------------------------------#
#                                                                              #
# 30/04/2015	- v1    - First release.                                       #
#                                                                              #
# 04/05/2015	- v1.1  - [ FIX ]  Better "error description" to the log file. #
#                                                                              #
# 03/12/2015	- v2    - [ FEATURE ]  Script  now  collect  info from Network #
#			  intarfaces.                                          #
#                                                                              #
# 04/14/2015	- v2.1  - [ FIX ] Fix  'Network  intarfaces'  json  format.    #
#			- [ FIX ] Better  output  in  'df'  command.           #
#                                                                              #
# 10/07/2016	- v3    - [ FIX ] Now  it  show  all  'Network  intarfaces' no #
#			  matter the name.                                     #
#                                                                              #
#			- [ FEATURE ] I/O  read and write informations for all #
#			  partitions.                                          #
#                                                                              #
#------------------------------------------------------------------------------#

#[ Variables ]-----------------------------------------------------------------#

# System Commands

LS=$(which ls)
DF=$(which df)
AWK=$(which awk)
CAT=$(which cat)
SED=$(which sed)
GREP=$(which grep)
DATE=$(which date)
HEAD=$(which head)

# System info

TIMESTAMP=$($DATE +%s)
HOSTNAME=$(hostname -s)
SCRIPTNAME=$(basename $0)

# System files

FILECPU="/proc/stat"
FILEMEM="/proc/meminfo"
FILELOAD="/proc/loadavg"
FILEIO="/proc/diskstats"
FILEUPTIME="/proc/uptime"
FILEPARTITIONS="/proc/partitions"

# Script Files

TINYAGENTDB=".tinyagentdb"
TINYAGENTLOG="tinyagent.log"

# Empty Variables

SCRIPTOUTPUT=""
UPDATEDBFILE=""

#[ Functions ]-----------------------------------------------------------------#

exiterrorfunc(){

	# Generic output function, show the message given,
	# and then exits with the given code.

	# Parse message and exit code
	EXITCODE=$(echo $@ | awk '{print $NF}')
	EXITMESSAGE=$(echo $@ | awk '{ $NF = ""; print $0}')
	echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - $EXITMESSAGE" >> $TINYAGENTLOG
	exit $EXITCODE

}

sysUltime(){

	SYSUPTIME=$($AWK -F\. '{print "{ \"uptime\": "$1" }"}' $FILEUPTIME)
	SCRIPTOUTPUT="$SYSUPTIME $SCRIPTOUTPUT"

}

sysLoad(){

	SYSLOAD=$($AWK '{print "{ \"loadavg\": [ { \"onemin\": "$1" }, { \"fivemin\": "$2" }, { \"tenmin\": "$3" } ] }"}' $FILELOAD)
	SCRIPTOUTPUT="$SYSLOAD, $SCRIPTOUTPUT"

}

sysCpuUsage(){

	SYSCPU=$($HEAD -1 $FILECPU | \
	$AWK '{print "{ \"cpuusage\": [ { \"user\": "$2" }, { \"system\": "$4" }, { \"wait\": "$6" } ] }"}')
	SCRIPTOUTPUT="$SYSCPU, $SCRIPTOUTPUT"

}

sysMemoryUsage(){

	SYSMEM=$($SED '/^\(MemTotal\|MemFree\|Buffers\|Cached\)/!d' $FILEMEM | \
	$SED ':a;$!N;s/\n//g;ta;s/kB//g;s/[ ]\{1,\}/ /g;s/ \([0-9]\{1,\}\) / \1, /g;s/.*/\L&/g;s/\([a-z]\{1,\}\)/"\1"/g' | \
	$AWK -F, '{print "{ \"memusage\" : [ { "$1" }, {"$2" }, {"$3" }, {"$4" } ] }"}')
	SCRIPTOUTPUT="$SYSMEM, $SCRIPTOUTPUT"

}

sysDiskUsage(){

	SYSDISK=$($DF -Pk | \
	$SED '/^\//!d' | \
	$AWK '{ print "{ \"mountpoint\": \""$NF"\", \"usage\" : [ { \"total\": "$2" }, { \"used\": "$3" }, { \"free\": "$4" } ] },"}' | \
	$SED ':a;$!N;s/\n/ /g;ta;s/,$//')
	SCRIPTOUTPUT="{ \"diskusage\" : [ $SYSDISK ] }, $SCRIPTOUTPUT"

}

sysIOStats(){

	IOSTATS=""
	PARTITIONS=$($SED '1,2d' $FILEPARTITIONS | $SED '/[a-z]\{1,\}[0-9]$/!d' | $AWK '{print $NF}')

	if [[ -e $TINYAGENTDB ]]; then
		source $TINYAGENTDB
		for i in ${PARTITIONS[@]} ; do
			PARTITION=$($GREP ${i} $FILEIO | $AWK '{ print $3}')
			TSRMS=$($GREP ${i} $FILEIO | $AWK '{ print $7}')
			TSWMS=$($GREP ${i} $FILEIO | $AWK '{ print $11}')
			TSIOMS=$($GREP ${i} $FILEIO | $AWK '{ print $13}')
			TSRAUX="TSRMS_$i"
			TSWAUX="TSWMS_$i"
			TSIOAUX="TSIOMS_$i"
			TSRMILLISECONDS=$(($TSRMS-${!TSRAUX}))
			TSWMILLISECONDS=$(($TSWMS-${!TSWAUX}))
			TSIOMILLISECONDS=$(($TSIOMS-${!TSIOAUX}))
			IOSTATS=$IOSTATS"{ \"partition\": \"$PARTITION\", \""$PARTITION"_time_spent_reading\": $TSRMILLISECONDS, \""$PARTITION"_time_spent_writing\": $TSWMILLISECONDS, \""$PARTITION"_time_spent_doing_io\": $TSIOMILLISECONDS },"
			UPDATEDBFILE=$UPDATEDBFILE"TSRMS_${i}=$TSRMS\nTSWMS_${i}=$TSWMS\nTSIOMS_${i}=$TSIOMS\n"
		done
	else
		for i in ${PARTITIONS[@]} ; do
			PARTITION=$($GREP ${i} $FILEIO | $AWK '{ print $3}')
			TSRMS=$($GREP ${i} $FILEIO | $AWK '{ print $7}')
			TSWMS=$($GREP ${i} $FILEIO | $AWK '{ print $11}')
			TSIOMS=$($GREP ${i} $FILEIO | $AWK '{ print $13}')
			TSRAUX="TSRMS_$i"
			TSWAUX="TSWMS_$i"
			TSIOAUX="TSIOMS_$i"
			IOSTATS=$IOSTATS"{ \"partition\": \"$PARTITION\", \""$PARTITION"_time_spent_reading\": 0, \""$PARTITION"_time_spent_writing\": 0, \""$PARTITION"_time_spent_doing_io\": 0 },"
			UPDATEDBFILE=$UPDATEDBFILE"TSRMS_${i}=$TSRMS\nTSWMS_${i}=$TSWMS\nTSIOMS_${i}=$TSIOMS\n"
		done
	fi

	IOSTATS=$(echo $IOSTATS | sed 's/,$//')
	SCRIPTOUTPUT="{ \"iostats\": [ $IOSTATS ] }, $SCRIPTOUTPUT"
	
}

sysNetworkUsage(){

	SYSNETTRAFFIC=""
	INTERFACELIST=$($LS -1 /sys/class/net/)

	if [[ -e $TINYAGENTDB ]]; then
		source $TINYAGENTDB
		for i in ${INTERFACELIST[@]} ; do
			RXBYTES=$(cat /sys/class/net/${i}/statistics/rx_bytes)
			TXBYTES=$(cat /sys/class/net/${i}/statistics/tx_bytes)
			RXAUX="RXBYTES_$i"
			TXAUX="TXBYTES_$i"
			RECEIVEDBYTES=$(($RXBYTES-${!RXAUX}))
			TRANSMITTEDBYTES=$(($TXBYTES-${!TXAUX}))
			SYSNETTRAFFIC=$SYSNETTRAFFIC"{ \"rx_${i}\": "$RECEIVEDBYTES" }, { \"tx_${i}\": $TRANSMITTEDBYTES }, "
			UPDATEDBFILE=$UPDATEDBFILE"RXBYTES_${i}=$RXBYTES\nTXBYTES_${i}=$TXBYTES\n"
		done
	else
		for i in ${INTERFACELIST[@]} ; do
			RXBYTES=$(cat /sys/class/net/${i}/statistics/rx_bytes)
			TXBYTES=$(cat /sys/class/net/${i}/statistics/tx_bytes)
			RXAUX="RXBYTES_$i"
			TXAUX="TXBYTES_$i"
			SYSNETTRAFFIC=$SYSNETTRAFFIC"{ \"rx_${i}\": 0 }, { \"tx_${i}\": 0 }, "
			UPDATEDBFILE=$UPDATEDBFILE"RXBYTES_${i}=$RXBYTES\nTXBYTES_${i}=$TXBYTES\n"
		done
	fi

	SYSNETTRAFFIC=${SYSNETTRAFFIC%, }
	SCRIPTOUTPUT="{ \"nettraffic\" : [ $SYSNETTRAFFIC ] }, $SCRIPTOUTPUT"

}

scriptOutput(){
	echo "{ \"tinyagent\": [ { \"hostname\" : \"$HOSTNAME\" }, { \"timestamp\" : $TIMESTAMP }, "$SCRIPTOUTPUT" ] }"
	echo -e $UPDATEDBFILE > $TINYAGENTDB
}

executionFlow(){

	sysUltime
	[ $? -eq 0 ] || exiterrorfunc "Something went wrong, check if the file $FILEUPTIME is accessible 1"
	wait
	sysLoad
	[ $? -eq 0 ] || exiterrorfunc "Something went wrong, check if the file $FILELOAD is accessible 1"
	wait
	sysCpuUsage
	[ $? -eq 0 ] || exiterrorfunc "Something went wrong, check if the file $FILECPU is accessible 1"
	wait
	sysMemoryUsage
	[ $? -eq 0 ] || exiterrorfunc "Something went wrong, check if the file $FILEMEM is accessible 1"
	wait
	sysDiskUsage
	[ $? -eq 0 ] || exiterrorfunc "Something went wrong, check partition table 1"
	wait
	sysIOStats
	[ $? -eq 0 ] || exiterrorfunc "Something went wrong, check if the files $FILEPARTITIONS and $FILEIO are accessible 1"
	wait
	sysNetworkUsage
	[ $? -eq 0 ] || exiterrorfunc "Something went wrong, check network interfaces configuration 1"
	scriptOutput $SCRIPTOUTPUT
	exiterrorfunc "all check operations were done successfully 0"

}

executionFlow
